### ISSUE TITLE
Geometry_Engine: Strange behaviour from Offset

### ISSUE THREAD

**Issue by kThorsager** [BHoM/BHoM_Engine#1868] opened 2020-06-29 11:09 UTC
#### Description:

For example, this outline kind of explodes out, and I'm sure there are more edge-cases which would be nice to resolve
![image](https://user-images.githubusercontent.com/53530468/85996977-d4223780-ba00-11ea-9f49-bd035a089a5c.png)

@LMarkowski think you wrote most of it, unsure of the extent of this problem

#### Test file(s):

https://burohappold.sharepoint.com/:u:/s/BHoM/EYRnedr3sFdIkVOPMxrHYtQBGoxnEB_SE-MMd5ZQk89Skw?e=8iLWhP

**Comment by LMarkowski** [comment] 2020-07-02 09:40
Hi @kThorsager,
As said in the initial PR (#1314) , I am aware that this method is not perfect. The idea behind it was to create a method working for the most of typical project cases. Therefore offset works best for convex shapes. For concave it can produce errors as in your case, but it should throw a relevant warning. I've listed my concerns and ideas for improvement in this issue #1333, but honestly I can't tell if I'll be capable of implementing them any soon.
Sorry for not being very helpful. 🙈 If there is a need to have a more error-proof offset method I can try to find some time to give it another try. But it may require rewriting the method from the top down.

**Comment by kThorsager** [comment] 2020-07-02 10:08
Ah, had missed that one, but my case is not critical and I can understand that this is not a simple method even now.

So mostly liked to capture this, to be picked up at some point 👍

**Comment by FraserGreenroyd** [comment] 2024-01-04 14:44
Closing as duplicate of #1333 which captures more information about offset issues.

**Closed by FraserGreenroyd** 2024-01-04 14:44 UTC
Labels: type:bug
