### ISSUE TITLE
Serialiser_Engine: Kellerman dll not found error

### ISSUE THREAD

**Issue by enarhi** [BHoM/BHoM_Engine#1654] opened 2020-04-12 23:30 UTC
#### Description:
Getting an error when opening Revit after building off the BHoM_Engine when it includes the Kellerman dll reference added in #1643 as per below, evne though the dll is in the BHoM assemblies folder as expected. Have not been able to dig deeply into it but I would assume similar issues exist elsewhere, if it is specific to https://github.com/BHoM/Revit_Toolkit we can move this issue there.

![image](https://user-images.githubusercontent.com/6752345/79082386-66f0e700-7cda-11ea-8974-cc654b7a3621.png)

#### Expected behaviour:
Revit opens as usual with BHoM Addin working.

#### Test file(s):
Build, open Revit 2020.

**Comment by FraserGreenroyd** [comment] 2020-04-13 00:20
Closing as duplicate of #1653

**Closed by FraserGreenroyd** 2020-04-13 00:20 UTC
Labels: type:bug
