### ISSUE TITLE
Geometry_Engine: Centroid from outline curves(s) with opening curve(s) in it.

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#1705] opened 2020-04-27 14:40 UTC
#### Description:

A method for calculating the combined centroid from a single or set of outline curve(s) and a list of opening curve(s) would be good to have in the Geometry_Engine. Need for it has been shown in various parts of the code, and done separately for those cases. Good to put in one place.

**Comment by kThorsager** [comment] 2020-04-28 11:42
Sound more like it should be a method acting on a `PlanarSurface` as some curves are counted as negative and sounds like you're referring to the centroid of the area

**Comment by IsakNaslundBh** [comment] 2020-04-28 12:58
yeah, the method for planar surface would fundamentally be the same, but was thinking it could be usefull to have it without a planar surface as well, as I have seen at least three other cases where it has been used besides planar surface.

**Comment by LMarkowski** [comment] 2020-07-17 11:36
So I've created something:

1. 

![image](https://user-images.githubusercontent.com/48125514/87779155-a3c60000-c82c-11ea-9921-1007457e5438.png)
![image](https://user-images.githubusercontent.com/48125514/87779190-b17b8580-c82c-11ea-96ba-016a5e73b7b3.png)

2. 

![image](https://user-images.githubusercontent.com/48125514/87779248-c9530980-c82c-11ea-9863-1797b21f65d4.png)
![image](https://user-images.githubusercontent.com/48125514/87779218-bd674780-c82c-11ea-8dce-aba5c6a11dfe.png)
(In 2. I couldn't find out how to find a centroid of multiple breps in gh, but for the purpose of the example it seems to be enough.)

The logic behind finding centroid of multiple elements is really simple. The question though is what we are actually trying to achieve. 😃 Working on `PlanarSurface` or `IPanel` is more simple being certain that input is correct. If we wanted to have any two lists of `ICurve` as an input we would have to recreate all the checks that are performed while creating a `PlanarSurface`. I see two main ways to do that:
1. Creating methods for `IEnumerable<PlanarSurface>` and `IEnumerable<IPanel>` (and maybe also single inputs) and forcing users to create them before finding a centroid.
2. Creating method having any two `ICurve` lists as input and recreating checks from panels. User than can extract internal and external edges from panels or there can be methods for panels and surfaces pointing to the main method working on lists. It generates overhead when user already had panels which than would be checked twice. 

Second one is naturally more flexible but it feels a bit wrong not to use what has been done for `PlanarSurface`.

PS. Couldn't there be a common interface for `IPanel` and `PlanarSurface` since they are geometrically the same thing?

**Comment by pawelbaran** [comment] 2020-07-17 12:11
@al-fisher @kThorsager @IsakNaslundBh I think we need a big picture overview to make a decision here. My thoughts are:
- creation of `PlanarSurface` on the fly might be tricky as the checks are quite heavy + may generate a lot of irrelevant warnings (plus what if one outline gets skipped?)
- limiting the method only to a pre-created `PlanarSurface` would be very limiting
- redoing the checks that would to large extent be a duplicate of checks done by `Create.PlanarSurface` does not sound like a perfect deal either

Maybe that should become an impulse to sort out the way in which we handle planar object in BHoM in general, starting from geometry primitives and ending on higher abstractions?

**Comment by IsakNaslundBh** [comment] 2020-08-04 08:22
The reason I opened this issue was that I needed it for different things at different times, and seen it needed for other things as well, using different objects. The use cases I have found so far, from the top of my head, are:

- Profiles
- PlanarSurface
- Panels

We do not have a interface that is common between all those three, hence, wondering if a method that simply takes Outline curves and opening curves as lists and calculates the full centroid based on that, than then could be called for all the three usecases could be of use?

Going via planar surface simply wont work for all Profile cases, as disjoint profiles are acceptable, plus the arguments given above about not wanting the overhead of all the checks.

So, getting the logic into a method accepting curves, that then can be called for all the other three cases would be my gut feeling of the best option here, unless there is a big downside to this that I am missing!

**Comment by LMarkowski** [comment] 2020-08-06 08:01
To return correct centroid location we need to be sure that the input curves are planar, coplanar, non self-intersecting and closed. I wanted to avoid repeating those checks on the level of creating object and then when calculating centroid.

Maybe we could have one private method `Centroid(extenralCurves, internalCurves)` that would be called by public methods for Profile, Panel and PlanarSurface. In that way we can be sure that input curves are correct, but also have one do-it-all method and there won't be unnecessarily repeated checks.

What do you think?

**Comment by pawelbaran** [comment] 2020-08-10 16:39
Having a private method may be problematic in case you want to use it in other class (which you suggested yourself @LMarkowski 🤣). Plus I would rather not write a method for structural panel, but rather for `IElement2D`.

But maybe we could keep `Centroid(extenralCurves, internalCurves)` public with description saying that this method assumes that the curves are planar and coplanar, taking the _trash input == trash output_ approach? Then specific implementations (e.g. for `PlanarSurface` or `IElement2D`) could handle case-specific checks, while being rather safe that the method will not be called from the UI (if I were the user, I would be too lazy to construct 2 separate lists of outlines 🐒).

What do you think @IsakNaslundBh @al-fisher?

**Closed** 2020-09-11 13:36 UTC
Labels: type:feature
