### ISSUE TITLE
Geometry_Engine: NurbsCurve Bounds gives no tight box

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#344] opened 2018-06-18 08:11 UTC
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by pawelbaran** [comment] 2019-03-07 16:46
@epignatelli is that still relevant? Is it related with #710 by any means?

**Comment by kThorsager** [comment] 2020-04-22 10:01
duplicate of #1097

**Comment by pawelbaran** [comment] 2020-04-22 10:09
Let's close it then

**Closed by pawelbaran** 2020-04-22 10:09 UTC
Labels: severity:medium, type:bug
