### ISSUE TITLE
Geometry_Engine: Mirror tests failing

### ISSUE THREAD

**Issue by epignatelli** [BHoM/BHoM_Engine#439] opened 2018-07-20 14:38 UTC
Test file in here: https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Geometry_Engine/Modify/Mirror.gh?csf=1&e=mkfXnU

Methods failing due to other issues:

- [ ] NurbsSurface #441
- [ ] PolYSurface #441

Methods not satisfying the test:

- [ ] Vector
- [ ] Plane
- [ ] CoordinateSystem
 - [ ] Circle
 - [ ] Extrusion
 - [ ] Loft
 - [ ] Pipe
 - [ ] CompositeGeometry

**Comment by Tom-Kingstone** [comment] 2024-01-04 14:56
After review of historic issues, this issue (the tests) cannot be replicated. It will be assumed that this has been solved since, and marked as can't reproduce. If the issue is still unresolved, this issue can be reopened.

**Closed by Tom-Kingstone** 2024-01-04 14:56 UTC
Labels: severity:medium, type:bug
