### ISSUE TITLE
Geometry_Engine: Missing methods for PlanarSurface

### ISSUE THREAD

**Issue by adecler** [BHoM/BHoM_Engine#1616] opened 2020-03-26 06:15 UTC
#### Broken rules:
All `I` methods that take an `IGeometry` or an `ISurface` as first input should have a corresponding method for all possible geometry/surface. This is not the case for `PlanarSurface`.

(This was highlighted in https://github.com/BHoM/Grasshopper_Toolkit/issues/489)

#### Suggestions to restore compliance:
Implement all missing geometry methods for PlanarSurface.

### Comments:
- @FraserGreenroyd, @awakeman , this is/will be part of the CI check you are doing on compiled code. So I'm flagging you up here in case you are already able to provide the full list of missing methods (potentially for more than PlanarSurface).
- Assigning @IsakNaslundBh and @pawelbaran since they were the ones assigned for the creation of the PlanarSurface (see https://github.com/BHoM/BHoM/issues/424) but feel free to reassign appropriately.

**Comment by pawelbaran** [comment] 2020-03-26 07:48
I will do it, there is a few others piled up that would be good to be resolved in one go:
- https://github.com/BHoM/BHoM/issues/676
- https://github.com/BHoM/BHoM_Engine/issues/1446
- https://github.com/BHoM/BHoM_Engine/issues/1567 (probably duplicate of this issue)

**Comment by IsakNaslundBh** [comment] 2020-03-26 07:50
```
        /***************************************************/

        public static PlanarSurface Transform(this PlanarSurface surface, TransformMatrix transform)
        {
            return new PlanarSurface
            {
                ExternalBoundary = surface.ExternalBoundary.ITransform(transform),
                InternalBoundaries = surface.InternalBoundaries.Select(x => x.ITransform(transform)).ToList()
            };
        }
```

in case you want to copy paste (know you know how to do it;))

**Comment by pawelbaran** [comment] 2020-05-25 09:10
@kThorsager is that still relevant or resolved with your recent work?

**Comment by kThorsager** [comment] 2020-05-26 07:12
I haven't reviewed all geometry methods to make sure planar surface is covered, only made it `IImmutable` and given it methods to support that.

So I doubt that it's resolved, but I may be wrong 🤞

**Comment by kThorsager** [comment] 2020-06-04 13:50
The remaining missing methods for `PlanarSurface`:

- [ ] Clone
- [ ] ClosestPoint
- [ ] IsEqual
- [ ] IsInPlane

**Closed** 2020-07-07 08:15 UTC
Labels: type:compliance
