### ISSUE TITLE
Geometry_Engine: Offset failing for some cases where it would be expected to work

### ISSUE THREAD

**Issue by enarhi** [BHoM/BHoM_Engine#2503] opened 2021-05-13 21:11 UTC
#### Description:
Some offset cases fail with input geometry of closed polycurves consisting of lines and arcs only.

#### Steps to reproduce:
Use the test script provided. Some offset fail where they should work.

#### Expected behaviour:
All offsets working, with the exception of edge cases such as short edge lengths where they may not currently be supported.

#### Test file(s):
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/BHoM_Engine/Geometry_Engine/%232503-OffsetCurvesFailing.gh?csf=1&web=1&e=9pqFGE

**Comment by albinber** [comment] 2024-01-04 15:23
Closing as a duplicate of #1333 which captures more information about the issue.

**Closed by albinber** 2024-01-04 15:23 UTC
Labels: type:bug
