### ISSUE TITLE
Matter_Engine: AggregateMaterialComposition runs a bit slow

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM_Engine#1742] opened 2020-05-05 16:00 UTC
#### Description:

Should ensure the hashes are only calculated once per material by storing the hashes and then post cleaning all of them off when finished.

**Comment by kThorsager** [comment] 2020-05-13 14:29
Duplicate of #1719 which I can admit was poorly named

**Closed** 2020-05-19 14:05 UTC
Labels: type:feature
