### ISSUE TITLE
Geometry_Engine: Add IElementXD rotations

### ISSUE THREAD

**Issue by rwemay** [BHoM/BHoM_Engine#1302] opened 2019-11-06 07:18 UTC
#### Description:

We have translation at the moment, would be good to include rotation. I previously raised a flag over this as rotating of analytical (or physical) objects can be risky - they may have properties associated to the geometry but not derived from it (which is not ideal in itself, but not sure we can rule it out). However, if when we implement rotation of objects as a specific set of methods, rather than only SetGeometry - as translate currently is, it would make it more transparent/explicit of an implementation each time, therefore less risky. We could also impose some methods for people to override I guess, which might help simplify the 'not implemented' messages. Note that when I added IElement1D to IFramingElement in the Physical oM, the Translate 1DElement modify method did not return a warning, just no geometry (should be separate issue raised).

**Comment by pawelbaran** [comment] 2019-11-07 09:44
Hi @rwemay, closing this one as a duplicate of the previous thread - will reactivate the latter.

**Closed by pawelbaran** 2019-11-07 09:44 UTC
Labels: severity:low, size:L, type:feature
