### ISSUE TITLE
BHoM_Engine: SetProperty does not update BHoM_Guid

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM_Engine#1812] opened 2020-05-27 12:17 UTC
#### Description:

As in the title: calling `SetProperty` does not change the `BHoM_Guid` of an object. This creates serious issues in project workflows, when multiple objects get treated as duplicates:

![image](https://user-images.githubusercontent.com/26874773/83017769-8478d680-a024-11ea-9b14-22466b34c7d1.png)

Not sure how much work would that be @adecler, but it would be great to have it sorted out in 3.2...

**Comment by pawelbaran** [comment] 2020-05-27 12:20
And a hacky workaround for now:

![image](https://user-images.githubusercontent.com/26874773/83018162-1da7ed00-a025-11ea-95a7-7cef247eb811.png)

**Comment by adecler** [comment] 2020-06-02 05:05
This is not a bug. 

This behaviour is by design as you might have guessed by the fact that `ShallowClone` has `newGuid` set to `false` by default. `SetProperty` first does a shallow clone before changing the property but keeps `newGuid` to `false`. 

The reason behind it is traceability of objects. Think of it this way: `BHoM_Guid` is the machine equivalent to`Name`. Both are there to identify and keep track of an object even if some of its properties have changed (otherwise we might as well just use a hash). `ShallowClone` doesn't change the `BHoM_Guid` of an object for the same reason it doesn't change its `Name`. 

It is also important to mention that `PropertyValue` is in the `Modify` namespace, not the `Create`. Trying to create objects with modify methods is strange to me. So a change on `SetProperty` would imply a review on all Modify methods since that is not how that category was originally understood.

As you can imagine, changing this now might break things for people that are relying on the `BHoM_Guid` for doing updates (e.g. external databases or even external software). So I cannot simply change the behaviour of `SetProperty`. 

Having a technical point that can be considered as a bug by a portion of the users is a point that needs to be addressed though. The most obvious solution seems to expose the `newGuid` argument in `SetProperty` as well but that means reviewing all Modify methods and I am not sure I like that. 

I have changed this to a question since it probably needs a proper discussion around it.

@al-fisher , @rwemay , @IsakNaslundBh , @FraserGreenroyd , @alelom , @epignatelli

**Comment by pawelbaran** [comment] 2020-06-02 08:16
Sounds good @adecler. An alternative could be to assign new Guid to newly created objects on `SetProperty`. Otherwise I would argue for `newGuid` being defaulted to `true` for UX purposes (which I guess can be argued opposite by the others).

**Comment by adecler** [comment] 2020-06-02 08:45
> An alternative could be to assign new Guid to newly created objects on `SetProperty`. Otherwise I would argue for `newGuid` being defaulted to `true` for UX purposes (which I guess can be argued opposite by the others).

Hard 'no' from me on both for the reason mentioned above.

**Comment by pawelbaran** [comment] 2020-06-02 08:59
Which reason? `SetProperty` called from the UI can create _new_ objects (see the first screenshot: one object turning into two). If they are new, how come they are expected to have same Guids? Imo this is a bug, because by definition, Guid should be unique to every object, while the current functionality does not provide that.

To push it further, what if I set 2 property values to a single object with a single `SetProperty` component, and then modify each of the resultant objects in a different manner? We end up with 2 different objects with same Guids.

Possibly it should be raised as a UI bug, but I wanted to stay as close to the source method as possible - happy to move over if you prefer.

**Comment by adecler** [comment] 2020-06-02 09:05
But that's the point, you are not creating new objects, you are modifying existing ones.

It seems that, the conversation here is not sufficient so we should probably have a meeting on that topic.

**Comment by pawelbaran** [comment] 2020-06-02 09:25
I understand that on the code level you are not creating a new object, but just modifying it, that makes sense. But what does not make sense is this:

![image](https://user-images.githubusercontent.com/26874773/83503385-461b6580-a4c3-11ea-806a-f9f6a9f40d33.png)

And that _is_ a bug. `SetProperty` should update Guid on the UI level, otherwise it cases a range of issues for the end user (it behaves differently than any other `Modify` method plus can lead to multiple objects with same Guids).

Happy to have a chat about that and happy to transfer the issue wherever it is suitable, but please do not remove bug label, because it is a bug all in all 🙊

**Comment by adecler** [comment] 2020-06-12 09:24
Following our group discussion, it was confirmed that `SetProperty` is demonstrating the expected behaviour.

To summarise the discussion around that point: the issue is that Grasshopper doesn't make a distinction between modify and create while the BHoM does. That distinction is important for the BHoM to work in all cases so cannot be ignored. To better highlight that fact and clarify expected behaviours to the user, we need to:
- better document in teh wiki the way BHoM_Guid, Name and Hash are ment to be used
- Improve descriptions on the BHoM_Guid property
- promote the hash method to the BHoM_Engine to make it more obvious and readily available

I will keep this issue open until those actions have been taken or raised as separate issues.

**Comment by adecler** [comment] 2020-11-17 05:38
Closing as handled in https://github.com/BHoM/admin/issues/9

**Closed by adecler** 2020-11-17 05:38 UTC
Labels: type:question
