### ISSUE TITLE
Geometry_Engine: IsPlanar returns true if the tolerance is set to it's default value

### ISSUE THREAD

**Issue by peterjamesnugent** [BHoM/BHoM_Engine#2356] opened 2021-02-26 14:10 UTC
#### Description:

If you have a non-planar `PlanarSurface` and use the `IsPlanar` method without specificying a tolerance, the result is always true - even if the `PlanarSurface` is not planar.

Relevant part of the code:
https://github.com/BHoM/BHoM_Engine/blob/a61fd36ebf1552b7eec569ef8b9621903ea685c2/Geometry_Engine/Query/IsPlanar.cs#L115-L117

Seems the stem of the issue (in relation to the test script) from the Analytical_Engine and the Geometry method there:
https://github.com/BHoM/BHoM_Engine/blob/97c734e1a6b908706da70c66ac7c334ffd648a26/Analytical_Engine/Query/Geometry.cs#L76-L90

#### Steps to reproduce:

See test file.

#### Expected behaviour:

`IsPlanar` to return `false` without specifying a tolerance.

#### Test file(s):

https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/BHoM_Engine/Geometry_Engine/%232356%20-IsPlanar-PlanarSurface.gh?csf=1&web=1&e=Ofa6el

**Comment by pawelbaran** [comment] 2021-03-01 17:10
As discussed today, this is not a bug on the Geometry_Engine side because `PlanarSurface` should always be planar within the default tolerance (it implements `IImmutable`). The actual origin of the issue is the fact that it is possible to create nonplanar structural panels and read their nonplanar surface through constructor instead of `Create` method (@IsakNaslundBh FYI, please feel free to raise a relevant issue).

I will keep this issue open and assigned to myself in order to resolve by adding a comment describing why is that meant to make sense (I will not dare to say it _makes_ sense 🙈).

**Closed** 2021-03-11 15:51 UTC
Labels: type:bug
